---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: container-selinux.spec

jobs:
  - &copr
    job: copr_build
    # Run on every PR
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    # x86_64 is assumed by default
    # container-selinux is noarch so we only need to test on one arch
    targets: &pr_copr_targets
      - fedora-rawhide
      - fedora-38
      - fedora-37
      - centos-stream-9
      - centos-stream-8
    srpm_build_deps:
      - make
      - rpkg
    actions:
      post-upstream-clone:
        - rpkg spec --outdir ./
      fix-spec-file:
        - bash .packit.sh

  - <<: *copr
    # Run on commit to main branch
    trigger: commit
    branch: main
    project: podman-next
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
      - fedora-rawhide-x86_64
      - fedora-38-aarch64
      - fedora-38-ppc64le
      - fedora-38-s390x
      - fedora-38-x86_64
      - fedora-37-aarch64
      - fedora-37-ppc64le
      - fedora-37-s390x
      - fedora-37-x86_64
      - centos-stream+epel-next-9-aarch64
      - centos-stream+epel-next-9-ppc64le
      - centos-stream+epel-next-9-s390x
      - centos-stream+epel-next-9-x86_64

  # All tests specified in the `/plans/` subdir
  # FIXME: uncomment e2e tests after disk space issues resolved on testing farm
  #- job: tests
  #  trigger: pull_request
  #  targets: *test_targets
  #  identifier: podman_e2e_test
  #  tmt_plan: "/plans/podman_e2e_test"

  - job: tests
    trigger: pull_request
    # arch assumed to be x86_64 by default.
    targets: *pr_copr_targets
    identifier: podman_system_test
    tmt_plan: "/plans/podman_system_test"
