# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: container-selinux.spec

jobs:
  - job: copr_build
    # Run on every PR
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make
      - rpkg
    actions:
      post-upstream-clone:
        - rpkg spec --outdir ./
      fix-spec-file:
        - bash .packit.sh
